### ISSUE TITLE
not installing 

### ISSUE THREAD

**Issue by swathigrate** [skoshy/YouTubeEXT#1]
hello sir ,

 i try to install bit it's not installing ...   giving some error 
i'm using Firefox 43 , grasemonkey  3.9 

try to fix it 
thanks you 
![df](https://cloud.githubusercontent.com/assets/14991260/18916323/b0b733c2-85b1-11e6-8f41-04dfaa7ea6e1.JPG)

**Comment by skoshy** [comment]
Should be working now! The match pattern that was specified in the script wasn't compatible with Greasemonkey. You might need to wait a bit for the cached script to refresh on Github.
